youtube_channels:
  crypto_analysis:
    - "cryptopourtous75"
    - "CryptoETBoursepourTous75"
    - "Hasheur"
    - "Crypto-wavetrading"
    - "mohamedadany"
    - "Bankless"
  macro_geopo:
    - "PerunAU"
    - "charles-gave"
    - "TheEconomist"
    - "CaspianReport"

channel_handles:
  cryptopourtous75: "@cryptopourtous75"
  CryptoETBoursepourTous75: "@CryptoETBoursepourTous75"
  Hasheur: "@Hasheur"
  PerunAU: "@PerunAU"
  Crypto-wavetrading: "@Crypto-wavetrading"
  mohamedadany: "@mohamedadany"
  charles-gave: "@charles-gave"
  Bankless: "@Bankless"
  TheEconomist: "@TheEconomist"
  CaspianReport: "@CaspianReport"

settings:
  max_age_hours: 24
  max_videos_per_channel: 3
